/**
 * @generated by packages/cli/scripts/sync-opencode-schema.ts
 * Source: https://opencode.ai/config.json
 *
 * DO NOT EDIT BY HAND. Refresh with: bun run scripts/sync-opencode-schema.ts
 *
 * Authoritative set of valid top-level opencode config fields (name -> shallow kind),
 * synced from opencode's published JSON Schema. `opencodeConfigSchema` builds on this:
 * it types the fields ocx manipulates precisely, passes other known fields through for
 * opencode to validate, and rejects top-level keys not listed here.
 */

export type OpencodeFieldKind = "string" | "number" | "boolean" | "array" | "object" | "unknown"

export const OPENCODE_CONFIG_FIELD_KINDS: Record<string, OpencodeFieldKind> = {
	$schema: "string",
	agent: "object",
	attachment: "object",
	autoshare: "boolean",
	autoupdate: "unknown",
	command: "object",
	compaction: "object",
	default_agent: "string",
	disabled_providers: "array",
	enabled_providers: "array",
	enterprise: "object",
	experimental: "object",
	formatter: "unknown",
	instructions: "array",
	layout: "string",
	logLevel: "string",
	lsp: "unknown",
	mcp: "object",
	mode: "object",
	model: "unknown",
	permission: "unknown",
	plugin: "array",
	provider: "object",
	reference: "object",
	references: "object",
	server: "object",
	share: "string",
	shell: "string",
	skills: "object",
	small_model: "unknown",
	snapshot: "boolean",
	subagent_depth: "number",
	tool_output: "object",
	tools: "object",
	username: "string",
	watcher: "object",
}
